// ATTENTION: This file is automatically generated. Do not edit manually.
#nullable enable
namespace GISharp.Lib.GLib
{
    /// <include file="OptionEntry.xmldoc" path="declaration/member[@name='OptionEntry']/*" />
    public partial struct OptionEntry
    {
#pragma warning disable CS0649
        /// <include file="OptionEntry.xmldoc" path="declaration/member[@name='LongName']/*" />
        public System.IntPtr LongName;

        /// <include file="OptionEntry.xmldoc" path="declaration/member[@name='ShortName']/*" />
        public System.SByte ShortName;

        /// <include file="OptionEntry.xmldoc" path="declaration/member[@name='Flags']/*" />
        public System.Int32 Flags;

        /// <include file="OptionEntry.xmldoc" path="declaration/member[@name='Arg']/*" />
        public GISharp.Lib.GLib.OptionArg Arg;

        /// <include file="OptionEntry.xmldoc" path="declaration/member[@name='ArgData']/*" />
        public System.IntPtr ArgData;

        /// <include file="OptionEntry.xmldoc" path="declaration/member[@name='Description']/*" />
        public System.IntPtr Description;

        /// <include file="OptionEntry.xmldoc" path="declaration/member[@name='ArgDescription']/*" />
        public System.IntPtr ArgDescription;
#pragma warning restore CS0649
    }
}