// SPDX-License-Identifier: MIT
// ATTENTION: This file is automatically generated. Do not edit manually.
#nullable enable
namespace GISharp.Lib.Gtk
{
    /// <include file="ConstraintRelation.xmldoc" path="declaration/member[@name='ConstraintRelation']/*" />
    [GISharp.Runtime.GTypeAttribute("GtkConstraintRelation", IsProxyForUnmanagedType = true)]
    public enum ConstraintRelation
    {
        /// <include file="ConstraintRelation.xmldoc" path="declaration/member[@name='ConstraintRelation.Le']/*" />
        Le = -1,
        /// <include file="ConstraintRelation.xmldoc" path="declaration/member[@name='ConstraintRelation.Eq']/*" />
        Eq = 0,
        /// <include file="ConstraintRelation.xmldoc" path="declaration/member[@name='ConstraintRelation.Ge']/*" />
        Ge = 1
    }

    /// <summary>
    /// Extension methods for <see cref="ConstraintRelation"/>.
    /// </summary>
    public static unsafe partial class ConstraintRelationExtensions
    {
        private static readonly GISharp.Runtime.GType _GType = gtk_constraint_relation_get_type();

        [System.Runtime.InteropServices.DllImportAttribute("gtk-4.1", CallingConvention = System.Runtime.InteropServices.CallingConvention.Cdecl)]
        /* <type name="GType" type="GType" /> */
        /* transfer-ownership:full direction:in */
        private static extern GISharp.Runtime.GType gtk_constraint_relation_get_type();
    }
}