// SPDX-License-Identifier: MIT
// ATTENTION: This file is automatically generated. Do not edit manually.
#nullable enable
namespace GISharp.Lib.Gtk
{
    /// <include file="Justification.xmldoc" path="declaration/member[@name='Justification']/*" />
    [GISharp.Runtime.GTypeAttribute("GtkJustification", IsProxyForUnmanagedType = true)]
    public enum Justification
    {
        /// <include file="Justification.xmldoc" path="declaration/member[@name='Justification.Left']/*" />
        Left = 0,
        /// <include file="Justification.xmldoc" path="declaration/member[@name='Justification.Right']/*" />
        Right = 1,
        /// <include file="Justification.xmldoc" path="declaration/member[@name='Justification.Center']/*" />
        Center = 2,
        /// <include file="Justification.xmldoc" path="declaration/member[@name='Justification.Fill']/*" />
        Fill = 3
    }

    /// <summary>
    /// Extension methods for <see cref="Justification"/>.
    /// </summary>
    public static unsafe partial class JustificationExtensions
    {
        private static readonly GISharp.Runtime.GType _GType = gtk_justification_get_type();

        [System.Runtime.InteropServices.DllImportAttribute("gtk-4.1", CallingConvention = System.Runtime.InteropServices.CallingConvention.Cdecl)]
        /* <type name="GType" type="GType" /> */
        /* transfer-ownership:full direction:in */
        private static extern GISharp.Runtime.GType gtk_justification_get_type();
    }
}