// SPDX-License-Identifier: MIT
// ATTENTION: This file is automatically generated. Do not edit manually.
#nullable enable
namespace GISharp.Lib.Gtk
{
    /// <include file="PropagationLimit.xmldoc" path="declaration/member[@name='PropagationLimit']/*" />
    [GISharp.Runtime.GTypeAttribute("GtkPropagationLimit", IsProxyForUnmanagedType = true)]
    public enum PropagationLimit
    {
        /// <include file="PropagationLimit.xmldoc" path="declaration/member[@name='PropagationLimit.None']/*" />
        None = 0,
        /// <include file="PropagationLimit.xmldoc" path="declaration/member[@name='PropagationLimit.SameNative']/*" />
        SameNative = 1
    }

    /// <summary>
    /// Extension methods for <see cref="PropagationLimit"/>.
    /// </summary>
    public static unsafe partial class PropagationLimitExtensions
    {
        private static readonly GISharp.Runtime.GType _GType = gtk_propagation_limit_get_type();

        [System.Runtime.InteropServices.DllImportAttribute("gtk-4.1", CallingConvention = System.Runtime.InteropServices.CallingConvention.Cdecl)]
        /* <type name="GType" type="GType" managed-name="GISharp.Runtime.GType" /> */
        /* transfer-ownership:full direction:in */
        private static extern GISharp.Runtime.GType gtk_propagation_limit_get_type();
    }
}