// SPDX-License-Identifier: MIT
// ATTENTION: This file is automatically generated. Do not edit manually.
#nullable enable
namespace GISharp.Lib.GLib
{
    /// <summary>
    /// Specifies the type of the function passed to g_hash_table_foreach().
    /// It is called with each key/value pair, together with the @user_data
    /// parameter which is passed to g_hash_table_foreach().
    /// </summary>
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
    [System.Runtime.InteropServices.UnmanagedFunctionPointerAttribute(System.Runtime.InteropServices.CallingConvention.Cdecl)]
    /* <type name="none" type="void" managed-name="System.Void" /> */
    /* transfer-ownership:none direction:in */
    public unsafe delegate void UnmanagedHFunc(
    /* <type name="gpointer" type="gpointer" managed-name="System.IntPtr" is-pointer="1" /> */
    /* transfer-ownership:none nullable:1 allow-none:1 direction:in */
    System.IntPtr key,
    /* <type name="gpointer" type="gpointer" managed-name="System.IntPtr" is-pointer="1" /> */
    /* transfer-ownership:none nullable:1 allow-none:1 direction:in */
    System.IntPtr value,
    /* <type name="gpointer" type="gpointer" managed-name="System.IntPtr" is-pointer="1" /> */
    /* transfer-ownership:none nullable:1 allow-none:1 closure:2 direction:in */
    System.IntPtr userData);

    /// <include file="HFunc.xmldoc" path="declaration/member[@name='HFunc']/*" />
    public delegate void HFunc(System.IntPtr key, System.IntPtr value);

    /// <summary>
    /// Class for marshalling <see cref="HFunc"/> methods.
    /// </summary>
    public static unsafe class HFuncMarshal
    {
        /// <summary>
        /// Marshals an unmanaged pointer to a <see cref="HFunc"/>.
        /// </summary>
        public static GISharp.Lib.GLib.HFunc FromPointer(delegate* unmanaged[Cdecl]<System.IntPtr, System.IntPtr, System.IntPtr, void> callback_, System.IntPtr userData_)
        {
            void managedCallback(System.IntPtr key, System.IntPtr value)
            {
                var key_ = (System.IntPtr)key;
                var value_ = (System.IntPtr)value;
                callback_(key_, value_, userData_);
            }

            return managedCallback;
        }

        /// <summary>
        /// For runtime use only.
        /// </summary>
        [System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
        public static void Callback(System.IntPtr key_, System.IntPtr value_, System.IntPtr userData_)
        {
            try
            {
                var key = (System.IntPtr)key_;
                var value = (System.IntPtr)value_;
                var userDataHandle = (System.Runtime.InteropServices.GCHandle)userData_;
                var (userData, userDataScope) = ((HFunc, GISharp.Runtime.CallbackScope))userDataHandle.Target!;
                userData.Invoke(key, value);
                if (userDataScope == GISharp.Runtime.CallbackScope.Async)
                {
                    userDataHandle.Free();
                }
            }
            catch (System.Exception ex)
            {
                GISharp.Lib.GLib.Log.LogUnhandledException(ex);
            }
        }
    }
}