// SPDX-License-Identifier: MIT
// ATTENTION: This file is automatically generated. Do not edit manually.
#nullable enable
namespace GISharp.Lib.GLib
{
    /// <include file="LogField.xmldoc" path="declaration/member[@name='LogField']/*" />
    [GISharp.Runtime.SinceAttribute("2.50")]
    public unsafe partial struct LogField
    {
#pragma warning disable CS0169, CS0414, CS0649
        /// <include file="LogField.xmldoc" path="declaration/member[@name='LogField.key']/*" />
        private readonly byte* key;

        /// <include file="LogField.xmldoc" path="declaration/member[@name='LogField.value']/*" />
        private readonly System.IntPtr value;

        /// <include file="LogField.xmldoc" path="declaration/member[@name='LogField.length']/*" />
        private readonly nint length;
#pragma warning restore CS0169, CS0414, CS0649
    }
}