// This file was originally generated by the Gtk# (gapi3) code generator.
// It is now maintained by hand.

using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace GISharp.GI
{
    public class CallbackInfo : CallableInfo
    {
        public CallbackInfo (IntPtr raw) : base (raw)
        {
        }
    }
}
