// This file was originally generated by the Gtk# (gapi3) code generator.
// It is now maintained by hand.

namespace GI
{

    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;

#region Autogenerated code
    public partial class CallableInfo : GI.BaseInfo
    {

        InfoCollection<ArgInfo> args;

        public InfoCollection<ArgInfo> Args {
            get {
                if (args == null) {
                    args = new InfoCollection<ArgInfo> (() => NArgs, GetArg);
                }
                return args;
            }
        }

        [DllImport ("libgirepository-1.0.dll", CallingConvention = CallingConvention.Cdecl)]
        static extern bool g_callable_info_can_throw_gerror (IntPtr raw);

        public bool CanThrowGError {
            get {
                bool raw_ret = g_callable_info_can_throw_gerror (Handle);
                bool ret = raw_ret;
                return ret;
            }
        }

        [DllImport ("libgirepository-1.0.dll", CallingConvention = CallingConvention.Cdecl)]
        static extern IntPtr g_callable_info_get_arg (IntPtr raw, int index);

        protected GI.ArgInfo GetArg (int index)
        {
            IntPtr raw_ret = g_callable_info_get_arg (Handle, index);
            GI.ArgInfo ret = MarshalPtr<ArgInfo> (raw_ret);
            return ret;
        }

        [DllImport ("libgirepository-1.0.dll", CallingConvention = CallingConvention.Cdecl)]
        static extern int g_callable_info_get_caller_owns (IntPtr raw);

        public GI.Transfer CallerOwns {
            get {
                int raw_ret = g_callable_info_get_caller_owns (Handle);
                GI.Transfer ret = (GI.Transfer)raw_ret;
                return ret;
            }
        }

        [DllImport ("libgirepository-1.0.dll", CallingConvention = CallingConvention.Cdecl)]
        static extern int g_callable_info_get_instance_ownership_transfer (IntPtr raw);

        public GI.Transfer InstanceOwnershipTransfer {
            get {
                int raw_ret = g_callable_info_get_instance_ownership_transfer (Handle);
                GI.Transfer ret = (GI.Transfer)raw_ret;
                return ret;
            }
        }

        [DllImport ("libgirepository-1.0.dll", CallingConvention = CallingConvention.Cdecl)]
        static extern int g_callable_info_get_n_args (IntPtr raw);

        protected int NArgs {
            get {
                int raw_ret = g_callable_info_get_n_args (Handle);
                int ret = raw_ret;
                return ret;
            }
        }

        [DllImport ("libgirepository-1.0.dll", CallingConvention = CallingConvention.Cdecl)]
        static extern IntPtr g_callable_info_get_return_attribute (IntPtr raw, IntPtr name);

        public string GetReturnAttribute (string name)
        {
            IntPtr native_name = MarshalG.StringToUtf8Ptr (name);
            IntPtr raw_ret = g_callable_info_get_return_attribute (Handle, native_name);
            string ret = MarshalG.Utf8PtrToString (raw_ret);
            MarshalG.Free (native_name);
            return ret;
        }

        [DllImport ("libgirepository-1.0.dll", CallingConvention = CallingConvention.Cdecl)]
        static extern IntPtr g_callable_info_get_return_type (IntPtr raw);

        public GI.TypeInfo ReturnTypeInfo {
            get {
                IntPtr raw_ret = g_callable_info_get_return_type (Handle);
                GI.TypeInfo ret = MarshalPtr<TypeInfo> (raw_ret);
                return ret;
            }
        }

        [DllImport ("libgirepository-1.0.dll", CallingConvention = CallingConvention.Cdecl)]
        static extern unsafe bool g_callable_info_invoke (IntPtr raw, IntPtr function, Argument[] in_args, int n_in_args, Argument[] out_args, int n_out_args, out Argument return_value, bool is_method, bool throws, out IntPtr error);

        public unsafe bool Invoke (IntPtr function, Argument[] inArgs, Argument[] outArgs, out Argument returnValue, bool isMethod, bool throws)
        {
            IntPtr error;
            bool ret = g_callable_info_invoke (Handle, function, inArgs, (inArgs == null ? 0 : inArgs.Length), outArgs, (outArgs == null ? 0 : outArgs.Length), out returnValue, isMethod, throws, out error);
            if (error != IntPtr.Zero)
                throw new GErrorException (error);
            return ret;
        }

        [DllImport ("libgirepository-1.0.dll", CallingConvention = CallingConvention.Cdecl)]
        static extern bool g_callable_info_is_method (IntPtr raw);

        public bool IsMethod {
            get {
                bool raw_ret = g_callable_info_is_method (Handle);
                bool ret = raw_ret;
                return ret;
            }
        }

        [DllImport ("libgirepository-1.0.dll", CallingConvention = CallingConvention.Cdecl)]
        static extern bool g_callable_info_iterate_return_attributes (IntPtr raw, ref AttributeIter iterator, out IntPtr name, out IntPtr value);

        public bool IterateReturnAttributes (ref GI.AttributeIter iterator, out string name, out string value)
        {
            IntPtr namePtr;
            IntPtr valuePtr;
            var ret = g_callable_info_iterate_return_attributes (Handle, ref iterator, out namePtr, out valuePtr);
            name = MarshalG.Utf8PtrToString (namePtr, freePtr: true);
            value = MarshalG.Utf8PtrToString (valuePtr, freePtr: true);
            return ret;
        }

        [DllImport ("libgirepository-1.0.dll", CallingConvention = CallingConvention.Cdecl)]
        static extern void g_callable_info_load_arg (IntPtr raw, int n, IntPtr arg);

        public void LoadArg (int n, GI.ArgInfo arg)
        {
            g_callable_info_load_arg (Handle, n, arg == null ? IntPtr.Zero : arg.Handle);
        }

        [DllImport ("libgirepository-1.0.dll", CallingConvention = CallingConvention.Cdecl)]
        static extern void g_callable_info_load_return_type (IntPtr raw, IntPtr type);

        public void LoadReturnType (GI.TypeInfo type)
        {
            g_callable_info_load_return_type (Handle, type == null ? IntPtr.Zero : type.Handle);
        }

        [DllImport ("libgirepository-1.0.dll", CallingConvention = CallingConvention.Cdecl)]
        static extern bool g_callable_info_may_return_null (IntPtr raw);

        public bool MayReturnNull {
            get {
                bool raw_ret = g_callable_info_may_return_null (Handle);
                bool ret = raw_ret;
                return ret;
            }
        }

        [DllImport ("libgirepository-1.0.dll", CallingConvention = CallingConvention.Cdecl)]
        static extern bool g_callable_info_skip_return (IntPtr raw);

        public bool SkipReturn {
            get {
                bool raw_ret = g_callable_info_skip_return (Handle);
                bool ret = raw_ret;
                return ret;
            }
        }

        public CallableInfo (IntPtr raw) : base (raw)
        {
        }

#endregion
    }
}
