// This file was originally generated by the Gtk# (gapi3) code generator.
// It is now maintained by hand.

namespace GI
{

    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;

#region Autogenerated code
    public partial class OptionGroup : GLib.Opaque
    {

        public OptionGroup (IntPtr raw) : base (raw)
        {
        }

#endregion
    }
}
