// This file was originally generated by the Gtk# (gapi3) code generator.
// It is now maintained by hand.

namespace GI
{

    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;

#region Autogenerated code
    public partial class ValueInfo : GI.BaseInfo
    {

        [DllImport ("libgirepository-1.0.dll", CallingConvention = CallingConvention.Cdecl)]
        static extern long g_value_info_get_value (IntPtr raw);

        public long Value {
            get {
                long raw_ret = g_value_info_get_value (Handle);
                long ret = raw_ret;
                return ret;
            }
        }

        public ValueInfo (IntPtr raw) : base (raw)
        {
        }

#endregion
    }
}
