// This file was generated by the Gtk# code generator.
// It is now maintained by hand.

namespace GI
{

    using System;
    using System.Runtime.InteropServices;

#region Autogenerated code
    [Flags]
    public enum VFuncInfoFlags
    {

        MustChainUp = 1 << 0,
        MustOverride = 1 << 1,
        MustNotOverride = 1 << 2,
        Throws = 1 << 3,
    }
#endregion
}
