// SPDX-License-Identifier: MIT
// Copyright (c) 2015-2019 David Lechner <david@lechnology.com>

// This file was originally generated by the Gtk# (gapi3) code generator.
// It is now maintained by hand.

using System;

namespace GISharp.Lib.GIRepository
{
    /// <summary>
    /// Represents a unresolved type in a typelib.
    /// </summary>
    /// <param name="raw">Raw.</param>
    public sealed class UnresolvedInfo : BaseInfo
    {
        public UnresolvedInfo (IntPtr raw) : base (raw)
        {
        }
    }
}
