// SPDX-License-Identifier: MIT
// ATTENTION: This file is automatically generated. Do not edit manually.
#nullable enable
namespace GISharp.Lib.GObject
{
    /// <include file="SignalQuery.xmldoc" path="declaration/member[@name='SignalQuery']/*" />
    public unsafe partial struct SignalQuery
    {
#pragma warning disable CS0169, CS0414, CS0649
        /// <include file="SignalQuery.xmldoc" path="declaration/member[@name='SignalQuery.signalId']/*" />
        private readonly uint signalId;

        /// <include file="SignalQuery.xmldoc" path="declaration/member[@name='SignalQuery.signalName']/*" />
        private readonly byte* signalName;

        /// <include file="SignalQuery.xmldoc" path="declaration/member[@name='SignalQuery.itype']/*" />
        private readonly GISharp.Runtime.GType itype;

        /// <include file="SignalQuery.xmldoc" path="declaration/member[@name='SignalQuery.signalFlags']/*" />
        private readonly GISharp.Lib.GObject.SignalFlags signalFlags;

        /// <include file="SignalQuery.xmldoc" path="declaration/member[@name='SignalQuery.returnType']/*" />
        private readonly GISharp.Runtime.GType returnType;

        /// <include file="SignalQuery.xmldoc" path="declaration/member[@name='SignalQuery.nParams']/*" />
        private readonly uint nParams;

        /// <include file="SignalQuery.xmldoc" path="declaration/member[@name='SignalQuery.paramTypes']/*" />
        private readonly GISharp.Runtime.GType* paramTypes;
#pragma warning restore CS0169, CS0414, CS0649
    }
}