// SPDX-License-Identifier: MIT
// ATTENTION: This file is automatically generated. Do not edit manually.
#nullable enable
namespace GISharp.Lib.GObject
{
    /// <include file="TypeFundamentalInfo.xmldoc" path="declaration/member[@name='TypeFundamentalInfo']/*" />
    public unsafe partial struct TypeFundamentalInfo
    {
#pragma warning disable CS0169, CS0414, CS0649
        /// <include file="TypeFundamentalInfo.xmldoc" path="declaration/member[@name='TypeFundamentalInfo.typeFlags']/*" />
        private readonly GISharp.Lib.GObject.TypeFundamentalFlags typeFlags;
#pragma warning restore CS0169, CS0414, CS0649
    }
}