// SPDX-License-Identifier: MIT
// ATTENTION: This file is automatically generated. Do not edit manually.
#nullable enable
namespace GISharp.Lib.GObject
{
    /// <include file="TypeValueTable.xmldoc" path="declaration/member[@name='TypeValueTable']/*" />
    public unsafe partial struct TypeValueTable
    {
#pragma warning disable CS0169, CS0414, CS0649
        /// <include file="TypeValueTable.xmldoc" path="declaration/member[@name='TypeValueTable.valueInit']/*" />
        private readonly delegate* unmanaged[Cdecl]<GISharp.Lib.GObject.Value*, void> valueInit;

        /// <include file="TypeValueTable.xmldoc" path="declaration/member[@name='TypeValueTable.valueFree']/*" />
        private readonly delegate* unmanaged[Cdecl]<GISharp.Lib.GObject.Value*, void> valueFree;

        /// <include file="TypeValueTable.xmldoc" path="declaration/member[@name='TypeValueTable.valueCopy']/*" />
        private readonly delegate* unmanaged[Cdecl]<GISharp.Lib.GObject.Value*, GISharp.Lib.GObject.Value*, void> valueCopy;

        /// <include file="TypeValueTable.xmldoc" path="declaration/member[@name='TypeValueTable.valuePeekPointer']/*" />
        private readonly delegate* unmanaged[Cdecl]<GISharp.Lib.GObject.Value*, System.IntPtr> valuePeekPointer;

        /// <include file="TypeValueTable.xmldoc" path="declaration/member[@name='TypeValueTable.collectFormat']/*" />
        private readonly byte* collectFormat;

        /// <include file="TypeValueTable.xmldoc" path="declaration/member[@name='TypeValueTable.collectValue']/*" />
        private readonly delegate* unmanaged[Cdecl]<GISharp.Lib.GObject.Value*, uint, GISharp.Lib.GObject.TypeCValue*, uint, byte*> collectValue;

        /// <include file="TypeValueTable.xmldoc" path="declaration/member[@name='TypeValueTable.lcopyFormat']/*" />
        private readonly byte* lcopyFormat;

        /// <include file="TypeValueTable.xmldoc" path="declaration/member[@name='TypeValueTable.lcopyValue']/*" />
        private readonly delegate* unmanaged[Cdecl]<GISharp.Lib.GObject.Value*, uint, GISharp.Lib.GObject.TypeCValue*, uint, byte*> lcopyValue;
#pragma warning restore CS0169, CS0414, CS0649
    }
}