// SPDX-License-Identifier: MIT
// ATTENTION: This file is automatically generated. Do not edit manually.
#nullable enable
namespace GISharp.Lib.Gtk
{
    /// <include file="BuilderClosureFlags.xmldoc" path="declaration/member[@name='BuilderClosureFlags']/*" />
    [GISharp.Runtime.GTypeAttribute("GtkBuilderClosureFlags", IsProxyForUnmanagedType = true)]
    [System.FlagsAttribute]
    public enum BuilderClosureFlags
    {
        /// <include file="BuilderClosureFlags.xmldoc" path="declaration/member[@name='BuilderClosureFlags.Swapped']/*" />
        Swapped = 0b0000_0000_0000_0000_0000_0000_0000_0001
    }

    /// <summary>
    /// Extension methods for <see cref="BuilderClosureFlags"/>.
    /// </summary>
    public static partial class BuilderClosureFlagsExtensions
    {
        private static readonly GISharp.Lib.GObject.GType _GType = gtk_builder_closure_flags_get_type();

        static partial void CheckGetGTypeArgs();
        [System.Runtime.InteropServices.DllImportAttribute("gtk-4.1", CallingConvention = System.Runtime.InteropServices.CallingConvention.Cdecl)]
        /* <type name="GType" type="GType" managed-name="GISharp.Lib.GObject.GType" /> */
        /* transfer-ownership:full direction:out */
        private static extern unsafe GISharp.Lib.GObject.GType gtk_builder_closure_flags_get_type();
    }
}