// ATTENTION: This file is automatically generated. Do not edit manually.
#nullable enable
namespace GISharp.Lib.Gtk
{
    /// <include file="MovementStep.xmldoc" path="declaration/member[@name='MovementStep']/*" />
    [GISharp.Runtime.GTypeAttribute("GtkMovementStep", IsProxyForUnmanagedType = true)]
    public enum MovementStep
    {
        /// <include file="MovementStep.xmldoc" path="declaration/member[@name='MovementStep.LogicalPositions']/*" />
        LogicalPositions = 0,
        /// <include file="MovementStep.xmldoc" path="declaration/member[@name='MovementStep.VisualPositions']/*" />
        VisualPositions = 1,
        /// <include file="MovementStep.xmldoc" path="declaration/member[@name='MovementStep.Words']/*" />
        Words = 2,
        /// <include file="MovementStep.xmldoc" path="declaration/member[@name='MovementStep.DisplayLines']/*" />
        DisplayLines = 3,
        /// <include file="MovementStep.xmldoc" path="declaration/member[@name='MovementStep.DisplayLineEnds']/*" />
        DisplayLineEnds = 4,
        /// <include file="MovementStep.xmldoc" path="declaration/member[@name='MovementStep.Paragraphs']/*" />
        Paragraphs = 5,
        /// <include file="MovementStep.xmldoc" path="declaration/member[@name='MovementStep.ParagraphEnds']/*" />
        ParagraphEnds = 6,
        /// <include file="MovementStep.xmldoc" path="declaration/member[@name='MovementStep.Pages']/*" />
        Pages = 7,
        /// <include file="MovementStep.xmldoc" path="declaration/member[@name='MovementStep.BufferEnds']/*" />
        BufferEnds = 8,
        /// <include file="MovementStep.xmldoc" path="declaration/member[@name='MovementStep.HorizontalPages']/*" />
        HorizontalPages = 9
    }

    /// <summary>
    /// Extension methods for <see cref="MovementStep"/>.
    /// </summary>
    public static partial class MovementStepExtensions
    {
        private static readonly GISharp.Lib.GObject.GType _GType = gtk_movement_step_get_type();

        static partial void CheckGetGTypeArgs();
        [System.Runtime.InteropServices.DllImportAttribute("gtk-4.0", CallingConvention = System.Runtime.InteropServices.CallingConvention.Cdecl)]
        /* <type name="GType" type="GType" managed-name="GISharp.Lib.GObject.GType" /> */
        /* transfer-ownership:full direction:out */
        private static extern unsafe GISharp.Lib.GObject.GType gtk_movement_step_get_type();
    }
}