// ATTENTION: This file is automatically generated. Do not edit manually.
#nullable enable
namespace GISharp.Lib.Gtk
{
    /// <include file="PrintStatus.xmldoc" path="declaration/member[@name='PrintStatus']/*" />
    [GISharp.Runtime.GTypeAttribute("GtkPrintStatus", IsProxyForUnmanagedType = true)]
    public enum PrintStatus
    {
        /// <include file="PrintStatus.xmldoc" path="declaration/member[@name='PrintStatus.Initial']/*" />
        Initial = 0,
        /// <include file="PrintStatus.xmldoc" path="declaration/member[@name='PrintStatus.Preparing']/*" />
        Preparing = 1,
        /// <include file="PrintStatus.xmldoc" path="declaration/member[@name='PrintStatus.GeneratingData']/*" />
        GeneratingData = 2,
        /// <include file="PrintStatus.xmldoc" path="declaration/member[@name='PrintStatus.SendingData']/*" />
        SendingData = 3,
        /// <include file="PrintStatus.xmldoc" path="declaration/member[@name='PrintStatus.Pending']/*" />
        Pending = 4,
        /// <include file="PrintStatus.xmldoc" path="declaration/member[@name='PrintStatus.PendingIssue']/*" />
        PendingIssue = 5,
        /// <include file="PrintStatus.xmldoc" path="declaration/member[@name='PrintStatus.Printing']/*" />
        Printing = 6,
        /// <include file="PrintStatus.xmldoc" path="declaration/member[@name='PrintStatus.Finished']/*" />
        Finished = 7,
        /// <include file="PrintStatus.xmldoc" path="declaration/member[@name='PrintStatus.FinishedAborted']/*" />
        FinishedAborted = 8
    }

    /// <summary>
    /// Extension methods for <see cref="PrintStatus"/>.
    /// </summary>
    public static partial class PrintStatusExtensions
    {
        private static readonly GISharp.Lib.GObject.GType _GType = gtk_print_status_get_type();

        static partial void CheckGetGTypeArgs();
        [System.Runtime.InteropServices.DllImportAttribute("gtk-4.1", CallingConvention = System.Runtime.InteropServices.CallingConvention.Cdecl)]
        /* <type name="GType" type="GType" managed-name="GISharp.Lib.GObject.GType" /> */
        /* transfer-ownership:full direction:out */
        private static extern unsafe GISharp.Lib.GObject.GType gtk_print_status_get_type();
    }
}