// ATTENTION: This file is automatically generated. Do not edit manually.
#nullable enable
namespace GISharp.Lib.Gio
{
    /// <include file="ApplicationFlags.xmldoc" path="declaration/member[@name='ApplicationFlags']/*" />
    [GISharp.Runtime.SinceAttribute("2.28")]
    [GISharp.Runtime.GTypeAttribute("GApplicationFlags", IsProxyForUnmanagedType = true)]
    [System.FlagsAttribute]
    public enum ApplicationFlags
    {
        /// <include file="ApplicationFlags.xmldoc" path="declaration/member[@name='FlagsNone']/*" />
        FlagsNone = 0b0000_0000_0000_0000_0000_0000_0000_0000,
        /// <include file="ApplicationFlags.xmldoc" path="declaration/member[@name='IsService']/*" />
        IsService = 0b0000_0000_0000_0000_0000_0000_0000_0001,
        /// <include file="ApplicationFlags.xmldoc" path="declaration/member[@name='IsLauncher']/*" />
        IsLauncher = 0b0000_0000_0000_0000_0000_0000_0000_0010,
        /// <include file="ApplicationFlags.xmldoc" path="declaration/member[@name='HandlesOpen']/*" />
        HandlesOpen = 0b0000_0000_0000_0000_0000_0000_0000_0100,
        /// <include file="ApplicationFlags.xmldoc" path="declaration/member[@name='HandlesCommandLine']/*" />
        HandlesCommandLine = 0b0000_0000_0000_0000_0000_0000_0000_1000,
        /// <include file="ApplicationFlags.xmldoc" path="declaration/member[@name='SendEnvironment']/*" />
        SendEnvironment = 0b0000_0000_0000_0000_0000_0000_0001_0000,
        /// <include file="ApplicationFlags.xmldoc" path="declaration/member[@name='NonUnique']/*" />
        [GISharp.Runtime.SinceAttribute("2.30")]
        NonUnique = 0b0000_0000_0000_0000_0000_0000_0010_0000,
        /// <include file="ApplicationFlags.xmldoc" path="declaration/member[@name='CanOverrideAppId']/*" />
        [GISharp.Runtime.SinceAttribute("2.48")]
        CanOverrideAppId = 0b0000_0000_0000_0000_0000_0000_0100_0000
    }

    /// <summary>
    /// Extension methods for <see cref="ApplicationFlags"/>.
    /// </summary>
    public partial class ApplicationFlagsExtensions
    {
        static readonly GISharp.Lib.GObject.GType _GType = g_application_flags_get_type();

        [System.Runtime.InteropServices.DllImportAttribute("gio-2.0", CallingConvention = System.Runtime.InteropServices.CallingConvention.Cdecl)]
        /* <type name="GType" type="GType" managed-name="GISharp.Lib.GObject.GType" /> */
        /* transfer-ownership:full direction:out */
        static extern unsafe GISharp.Lib.GObject.GType g_application_flags_get_type();
    }
}