// ATTENTION: This file is automatically generated. Do not edit by manually.
namespace GISharp.Lib.GLib
{
    /// <summary>
    /// Flags which influence the parsing.
    /// </summary>
    [System.FlagsAttribute]
    public enum KeyFileFlags
    {
        /// <summary>
        /// No flags, default behaviour
        /// </summary>
        None = 0b0000_0000_0000_0000_0000_0000_0000_0000,
        /// <summary>
        /// Use this flag if you plan to write the
        ///     (possibly modified) contents of the key file back to a file;
        ///     otherwise all comments will be lost when the key file is
        ///     written back.
        /// </summary>
        KeepComments = 0b0000_0000_0000_0000_0000_0000_0000_0001,
        /// <summary>
        /// Use this flag if you plan to write the
        ///     (possibly modified) contents of the key file back to a file;
        ///     otherwise only the translations for the current language will be
        ///     written back.
        /// </summary>
        KeepTranslations = 0b0000_0000_0000_0000_0000_0000_0000_0010
    }
}