
### ApplicationCommandLine ###

# File type is not implemented yet
- !set-attribute
  name: introspectable
  value: 0
  xpath: gi:repository/gi:namespace/gi:class[@name='ApplicationCommandLine']/gi:method[@name='create_file_for_arg']


# better names
- !set-attribute
  name: name
  value: get_options
  xpath: gi:repository/gi:namespace/gi:class[@name='ApplicationCommandLine']/gi:method[@name='get_options_dict']
- !set-attribute
  name: name
  value: get_environment
  xpath: gi:repository/gi:namespace/gi:class[@name='ApplicationCommandLine']/gi:method[@name='get_environ']
- !set-attribute
  name: name
  value: get_environment_variable
  xpath: gi:repository/gi:namespace/gi:class[@name='ApplicationCommandLine']/gi:method[@name='getenv']

# Don't need private struct
- !set-attribute
  name: introspectable
  value: 0
  xpath: gi:repository/gi:namespace/gi:record[@name='ApplicationCommandLinePrivate']
