
### ApplicationCommandLine ###

# better names
- !set-attribute
  name: name
  value: get_options
  xpath: gi:repository/gi:namespace/gi:class[@name='ApplicationCommandLine']/gi:method[@name='get_options_dict']
- !set-attribute
  name: name
  value: get_environment
  xpath: gi:repository/gi:namespace/gi:class[@name='ApplicationCommandLine']/gi:method[@name='get_environ']
- !set-attribute
  name: name
  value: get_environment_variable
  xpath: gi:repository/gi:namespace/gi:class[@name='ApplicationCommandLine']/gi:method[@name='getenv']

# fix null-terminated
- !set-attribute
  name: null-terminated
  value: 1
  xpath: gi:repository/gi:namespace/gi:class[@name='ApplicationCommandLine']/gi:method[@name='get_arguments']/gi:return-value/gi:array
