
### Application ###

# DBusConnection type is not implemented yet
- !set-attribute
  name: introspectable
  value: 0
  xpath: gi:repository/gi:namespace/gi:class[@name='Application']/*[gi:return-value/gi:type[@name='DBusConnection']]
- !set-attribute
  name: introspectable
  value: 0
  xpath: gi:repository/gi:namespace/gi:class[@name='Application']/*[gi:parameters/gi:parameter/gi:type[@name='DBusConnection']]
- !set-attribute
  name: introspectable
  value: 0
  xpath: gi:repository/gi:namespace/gi:record[@name='ApplicationClass']/gi:field[gi:callback/gi:parameters/gi:parameter/gi:type[@name='DBusConnection']]

# Notification type is not implemented yet
- !set-attribute
  name: introspectable
  value: 0
  xpath: gi:repository/gi:namespace/gi:class[@name='Application']/gi:method[@name='send_notification']

# Make application id getter return type match setter argument type
- !set-attribute
  name: nullable
  value: 1
  xpath: gi:repository/gi:namespace/gi:class[@name='Application']/gi:method[@name='get_application_id']/gi:return-value

# better event name for signal
- !set-attribute
  name: gs:managed-name
  value: HandledLocalOptions
  xpath: gi:repository/gi:namespace/gi:class[@name='Application']/glib:signal[@name='handle-local-options']
